//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FontAwesome6.Svg.Shared;

using Newtonsoft.Json;

using System.Collections.Generic;
using System.IO;
using System.Reflection;

namespace FontAwesome6.Svg
{
  public static class FontAwesomeSvg
  {
    public static Dictionary<string, FontAwesomeSvgInformation> Data = new Dictionary<string, FontAwesomeSvgInformation>();

    static FontAwesomeSvg()
    {
#if !FontAwesomePro
      LoadFromResource("FontAwesome6.Svg.FontAwesomeSvg.json", Assembly.GetExecutingAssembly());
#endif
    }

    public static void LoadFromResource(string resourceName, Assembly assembly)
    {      
      using (Stream stream = assembly.GetManifestResourceStream(resourceName))
      using (StreamReader reader = new StreamReader(stream))
      {
        string result = reader.ReadToEnd();
        Data = JsonConvert.DeserializeObject<Dictionary<string, FontAwesomeSvgInformation>>(result);
      }
    }

    public static void LoadFromDirectory(string path)
    {
      if (!File.Exists(path))
      {
        throw new System.Exception("File not found.");
      }

      Data = JsonConvert.DeserializeObject<Dictionary<string, FontAwesomeSvgInformation>>(File.ReadAllText(path));
    }
  }
}
