//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace FontAwesome6
{
	/// <summary>
	/// FontAwesome by Dave Gandy (@davegandy)
	///	The iconic SVG, font, and CSS toolkit
	///	License https://fontawesome.com/license (C#: MIT License)
	/// Version: 6.1.2 
	/// </summary>
	public enum EFontAwesomeStyle
	{
		/// <summary>
		/// This Style is used as an undefined state.
		/// </summary>
		None,		
		/// <summary>
		/// FontAwesome5 Solid Style
		/// </summary>
		Solid,
		/// <summary>
		/// FontAwesome5 Brands Style
		/// </summary>
		Brands,
		/// <summary>
		/// FontAwesome5 Regular Style
		/// </summary>
		Regular,

#if FontAwesomePro
		/// <summary>
		/// FontAwesome5 Light Style
		/// </summary>
		Light,
		/// <summary>
		/// FontAwesome5 Thin Style
		/// </summary>
		Thin,
		/// <summary>
		/// FontAwesome5 Duotone Style
		/// </summary>
		Duotone,
#endif
	}
}